// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkFg5xHR763DpHeBqVtsxTVHsUdPmFAsA',
    appId: '1:167123506337:web:d38908baf7f33e43cf4ce0',
    messagingSenderId: '167123506337',
    projectId: 'enoticeboard-e479c',
    authDomain: 'enoticeboard-e479c.firebaseapp.com',
    storageBucket: 'enoticeboard-e479c.appspot.com',
    measurementId: 'G-KM05YWR8KT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpWIkyp3Hyyt42KLP5vtudAM8_gP7NSB8',
    appId: '1:167123506337:android:1147efd110563e18cf4ce0',
    messagingSenderId: '167123506337',
    projectId: 'enoticeboard-e479c',
    storageBucket: 'enoticeboard-e479c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJgdo6aki2tQOQwxJLsfu7RsNlurfhf4k',
    appId: '1:167123506337:ios:bf8a480a1232c7eecf4ce0',
    messagingSenderId: '167123506337',
    projectId: 'enoticeboard-e479c',
    storageBucket: 'enoticeboard-e479c.appspot.com',
    iosBundleId: 'com.example.enoticeboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJgdo6aki2tQOQwxJLsfu7RsNlurfhf4k',
    appId: '1:167123506337:ios:39af8342e29596c4cf4ce0',
    messagingSenderId: '167123506337',
    projectId: 'enoticeboard-e479c',
    storageBucket: 'enoticeboard-e479c.appspot.com',
    iosBundleId: 'com.example.enoticeboard.RunnerTests',
  );
}
